"""
Foundry AI — Pydantic Schemas
Request/response schemas for the API layer.
"""

from pydantic import BaseModel, Field
from typing import Optional, Any
from datetime import datetime


# ─── Idea Input ───────────────────────────────────────────

class IdeaSubmission(BaseModel):
    """Schema for submitting a new project idea."""
    idea: str = Field(..., min_length=10, max_length=5000, description="The product idea to build")


class ProjectResponse(BaseModel):
    """Response after submitting an idea."""
    id: str
    idea: str
    status: str
    created_at: datetime


# ─── Council Schemas ──────────────────────────────────────

class CouncilDecisionResponse(BaseModel):
    """A single council decision."""
    id: str
    phase: str
    model_name: str
    role: str
    content: dict
    created_at: datetime


class PRDOutput(BaseModel):
    """Product Requirements Document generated by council."""
    project_name: str
    problem_statement: str
    target_users: list[str]
    core_features: list[dict[str, str]]
    technical_requirements: list[str]
    success_metrics: list[str]
    constraints: list[str]


class ArchitectureOutput(BaseModel):
    """System architecture designed by council."""
    system_name: str
    components: list[dict[str, Any]]
    data_flow: list[dict[str, str]]
    tech_stack: dict[str, str]
    api_endpoints: list[dict[str, str]]
    database_entities: list[dict[str, Any]]


# ─── Agent Schemas ────────────────────────────────────────

class AgentTaskResponse(BaseModel):
    """An agent task with its current status."""
    id: str
    agent_type: str
    task_name: str
    description: str
    status: str
    output_data: Optional[dict] = None
    error_message: Optional[str] = None
    retry_count: int = 0
    created_at: datetime
    updated_at: datetime


class AgentTaskAssignment(BaseModel):
    """Task assignment from council to an agent."""
    task: str
    assigned_agent: str
    framework: Optional[str] = None
    description: str
    dependencies: list[str] = []
    priority: int = 1
    input_context: dict = {}


# ─── Project Detail ───────────────────────────────────────

class ProjectDetail(BaseModel):
    """Full project detail including council decisions and agent tasks."""
    id: str
    idea: str
    status: str
    prd: Optional[dict] = None
    architecture: Optional[dict] = None
    schema_contract: Optional[dict] = None
    agent_plan: Optional[dict] = None
    project_structure: Optional[dict] = None
    council_decisions: list[CouncilDecisionResponse] = []
    agent_tasks: list[AgentTaskResponse] = []
    created_at: datetime
    updated_at: datetime


# ─── Log Schemas ──────────────────────────────────────────

class LogEntry(BaseModel):
    """A project log entry."""
    id: str
    source: str
    level: str
    message: str
    metadata: Optional[dict] = None
    created_at: datetime


# ─── WebSocket Events ────────────────────────────────────

class WSEvent(BaseModel):
    """WebSocket event sent to frontend."""
    event: str
    project_id: str
    data: dict = {}
    timestamp: datetime = Field(default_factory=datetime.utcnow)
